src/Entity/Restaurateur.php
<?php

namespace App\Entity;

use App\Repository\RestaurateurRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurateurRepository::class)
 */
class Restaurateur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mot_de_passe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_tel;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): self
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    
}

src/Form/RestaurateurType.php
<?php

namespace App\Form;


use App\Entity\Restaurateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;


class RestaurateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class,['label' =>'le nom :'])
            ->add('prenom',TextType::class,['label' =>'le prenom :'])
            ->add('email',TextType::class,['label' =>'email :'])
            ->add('mot_de_passe',TextType::class,['label' =>'mot de passe :'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurateur::class,
        ]);
    }
}

src/Controller/RestaurateurController.php
<?php

namespace App\Controller;

use App\Entity\Restaurateur;
use App\Form\RestaurateurType;
use App\Repository\RestaurateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/restaurateur")
 */
class RestaurateurController extends AbstractController
{
    /**
     * @Route("/", name="app_restaurateur_index", methods={"GET"})
     */
    public function index(RestaurateurRepository $restaurateurRepository): Response
    {
        return $this->render('restaurateur/index.html.twig', [
            'restaurateurs' => $restaurateurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_restaurateur_new", methods={"GET", "POST"})
     */
    public function new(Request $request, RestaurateurRepository $restaurateurRepository): Response
    {
        $restaurateur = new Restaurateur();
        $form = $this->createForm(RestaurateurType::class, $restaurateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restaurateurRepository->add($restaurateur, true);

            return $this->redirectToRoute('app_restaurateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurateur/new.html.twig', [
            'restaurateur' => $restaurateur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_restaurateur_show", methods={"GET"})
     */
    public function show(Restaurateur $restaurateur): Response
    {
        return $this->render('restaurateur/show.html.twig', [
            'restaurateur' => $restaurateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_restaurateur_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Restaurateur $restaurateur, RestaurateurRepository $restaurateurRepository): Response
    {
        $form = $this->createForm(RestaurateurType::class, $restaurateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restaurateurRepository->add($restaurateur, true);

            return $this->redirectToRoute('app_restaurateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurateur/edit.html.twig', [
            'restaurateur' => $restaurateur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_restaurateur_delete", methods={"POST"})
     */
    public function delete(Request $request, Restaurateur $restaurateur, RestaurateurRepository $restaurateurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurateur->getId(), $request->request->get('_token'))) {
            $restaurateurRepository->remove($restaurateur, true);
        }

        return $this->redirectToRoute('app_restaurateur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/restaurateur/_delete_form.html.twig
<form method="post" action="{{ path('app_restaurateur_delete', {'id': restaurateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurateur.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/restaurateur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
 <button class="btn btn-success">{{ button_label|default('Save') }} </button>  
  {{ form_end(form) }}

templates/restaurateur/edit.html.twig
{% block title %}Edit Restaurateur{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

{% endblock %}

{% block body %}
    <h1>Edit Restaurateur</h1>

    {{ include('restaurateur/_form.html.twig', {'button_label': 'Update'}) }}
<button class="btn btn-warning">
    <a href="{{ path('app_restaurateur_index') }}">back to list</a>
    </button>

    {{ include('restaurateur/_delete_form.html.twig') }}
{% endblock %}

templates/restaurateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurateur index{% endblock %}

{% block body %}
    <h1>Restaurateur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Mot_de_passe</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for restaurateur in restaurateurs %}
            <tr>
                <td>{{ restaurateur.id }}</td>
                <td>{{ restaurateur.nom }}</td>
                <td>{{ restaurateur.prenom }}</td>
                <td>{{ restaurateur.email }}</td>
                <td>{{ restaurateur.motDePasse }}</td>
                <td>
                    <a href="{{ path('app_restaurateur_show', {'id': restaurateur.id}) }}">show</a>
                    <a href="{{ path('app_restaurateur_edit', {'id': restaurateur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_restaurateur_new') }}">Create new</a>
{% endblock %}

templates/restaurateur/new.html.twig
{% block title %}New Restaurateur{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}

{% block body %}
    <h1>Create new Restaurateur</h1>

    {{ include('restaurateur/_form.html.twig') }}

    <a href="{{ path('app_restaurateur_index') }}">back to list</a>
{% endblock %}

templates/restaurateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurateur{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}

{% block body %}
    <h1>Restaurateur</h1>

    <table class="table table-success table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ restaurateur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ restaurateur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ restaurateur.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ restaurateur.email }}</td>
            </tr>
            <tr>
                <th>Mot_de_passe</th>
                <td>{{ restaurateur.motDePasse }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_restaurateur_index') }}">back to list</a>

    <a href="{{ path('app_restaurateur_edit', {'id': restaurateur.id}) }}">edit</a>

    {{ include('restaurateur/_delete_form.html.twig') }}
{% endblock %}