src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categorie;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_telephone;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\OneToMany(targetEntity=Menu::class, mappedBy="restaurant")
     */
    private $Menu;

    /**
     * @ORM\ManyToOne(targetEntity=Reservation::class, inversedBy="resto")
     */
    private $nom_resto;

    public function __construct()
    {
        $this->Menu = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPhotos(): ?string
    {
        return $this->photos;
    }

    public function setPhotos(string $photos): self
    {
        $this->photos = $photos;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getNumeroTelephone(): ?int
    {
        return $this->numero_telephone;
    }

    public function setNumeroTelephone(int $numero_telephone): self
    {
        $this->numero_telephone = $numero_telephone;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * @return Collection<int, Menu>
     */
    public function getMenu(): Collection
    {
        return $this->Menu;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->Menu->contains($menu)) {
            $this->Menu[] = $menu;
            $menu->setRestaurant($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->Menu->removeElement($menu)) {
            // set the owning side to null (unless already changed)
            if ($menu->getRestaurant() === $this) {
                $menu->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getNomResto(): ?Reservation
    {
        return $this->nom_resto;
    }

    public function setNomResto(?Reservation $nom_resto): self
    {
        $this->nom_resto = $nom_resto;

        return $this;
    }
}

src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\Restaurant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('photos')
            ->add('adresse')
            ->add('categorie')
            ->add('numero_telephone')
            ->add('rating')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Form\RestaurantType;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/restaurant")
 */
class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="app_restaurant_index", methods={"GET"})
     */
    public function index(RestaurantRepository $restaurantRepository): Response
    {
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_restaurant_new", methods={"GET", "POST"})
     */
    public function new(Request $request, RestaurantRepository $restaurantRepository): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restaurantRepository->add($restaurant, true);

            return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_restaurant_show", methods={"GET"})
     */
    public function show(Restaurant $restaurant): Response
    {
        return $this->render('restaurant/show.html.twig', [
            'restaurant' => $restaurant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_restaurant_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Restaurant $restaurant, RestaurantRepository $restaurantRepository): Response
    {
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $restaurantRepository->add($restaurant, true);

            return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_restaurant_delete", methods={"POST"})
     */
    public function delete(Request $request, Restaurant $restaurant, RestaurantRepository $restaurantRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurant->getId(), $request->request->get('_token'))) {
            $restaurantRepository->remove($restaurant, true);
        }

        return $this->redirectToRoute('app_restaurant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('app_restaurant_delete', {'id': restaurant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/restaurant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/restaurant/edit.html.twig
{% block title %}Edit Restaurant{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}
{% block body %}
    <h1>Edit Restaurant</h1>

    {{ include('restaurant/_form.html.twig', {'button_label': 'Update'}) }}
<button class="btn btn-warning">

    <a href="{{ path('app_restaurant_index') }}">back to list</a>
</button>
    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}

templates/restaurant/index.html.twig
{% block title %}Restaurant index{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}
{% block body %}
    <h1>Votre Restaurants</h1>

    <table class="table table-success table-striped">
       
        <tbody>
        {% for restaurant in restaurants %}
            <tr>
                <th>Id</th>
                <td>{{ restaurant.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ restaurant.nom }}</td>
            </tr>
            <tr>
                <th>Photos</th>
                <td>{{ restaurant.photos }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ restaurant.adresse }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ restaurant.categorie }}</td>
            </tr>
            <tr>
                <th>Numero_telephone</th>
                <td>{{ restaurant.numeroTelephone }}</td>
            </tr>
            <tr>
                <th>Rating</th>
                <td>{{ restaurant.rating }}</td>
            </tr>
            <td>actions</td><td>
                    <a href="{{ path('app_restaurant_show', {'id': restaurant.id}) }}">show</a>
                    <a href="{{ path('app_menu_new',{'id_restaurant': restaurant.id})}}">Create new menu</a>
                   <a href="{{ path('app_reservation_new'),{'id_restaurant': restaurant.id} }}">Create new reservation</a>
                    <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>
                   <a href="{{ path('app_restaurant_new') }}">Create new</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/restaurant/new.html.twig
{% block title %}New Restaurant{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}

{% block body %}
    <h1>Create new Restaurant</h1>

    {{ include('restaurant/_form.html.twig') }}

    <a href="{{ path('app_restaurant_index') }}">back to list</a>
{% endblock %}

templates/restaurant/show.html.twig
{% block title %}Restaurant{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}

{% block body %}
    <h1>Restaurant</h1>

    <table class="table table-success table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ restaurant.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ restaurant.nom }}</td>
            </tr>
            <tr>
                <th>Photos</th>
                <td>{{ restaurant.photos }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ restaurant.adresse }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ restaurant.categorie }}</td>
            </tr>
            <tr>
                <th>Numero_telephone</th>
                <td>{{ restaurant.numeroTelephone }}</td>
            </tr>
            <tr>
                <th>Rating</th>
                <td>{{ restaurant.rating }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_restaurant_index') }}">back to list</a>

    <a href="{{ path('app_restaurant_edit', {'id': restaurant.id}) }}">edit</a>

    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}