src/Entity/Menu.php
<?php

namespace App\Entity;

use App\Repository\MenuRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MenuRepository::class)
 */
class Menu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_restaurant;

    /**
     * @ORM\ManyToOne(targetEntity=Restaurant::class, inversedBy="Menu")
     */
    private $restaurant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getlibelle(): ?string
    {
        return $this->libelle;
    }

    public function setlibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getIdRestaurant(): ?int
    {
        return $this->id_restaurant;
    }

    public function setIdRestaurant(int $id_restaurant): self
    {
        $this->id_restaurant = $id_restaurant;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): self
    {
        $this->restaurant = $restaurant;

        return $this;
    }
}

src/Form/MenuType.php
<?php

namespace App\Form;

use App\Entity\Menu;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class MenuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle',TextType::class,['label' =>'le nom de menu:'])
            ->add('id_restaurant',TextType::class,['label' =>'id resto :'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Menu::class,
        ]);
    }
}

src/Controller/MenuController.php
<?php

namespace App\Controller;

use App\Entity\Menu;
use App\Form\MenuType;
use App\Repository\MenuRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/menuu")
 */
class MenuController extends AbstractController
{
    /**
     * @Route("/", name="app_menu_index", methods={"GET"})
     */
    public function index(MenuRepository $menuRepository): Response
    {
        return $this->render('menu/index.html.twig', [
            'menus' => $menuRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_menu_new", methods={"GET", "POST"})
     */
    public function new(Request $request, MenuRepository $menuRepository): Response
    {
        $menu = new Menu();
        $form = $this->createForm(MenuType::class, $menu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $menuRepository->add($menu, true);

            return $this->redirectToRoute('app_menu_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('menu/new.html.twig', [
            'menu' => $menu,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_menu_show", methods={"GET"})
     */
    public function show(Menu $menu): Response
    {
        return $this->render('menu/show.html.twig', [
            'menu' => $menu,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_menu_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Menu $menu, MenuRepository $menuRepository): Response
    {
        $form = $this->createForm(MenuType::class, $menu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $menuRepository->add($menu, true);

            return $this->redirectToRoute('app_menu_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('menu/edit.html.twig', [
            'menu' => $menu,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_menu_delete", methods={"POST"})
     */
    public function delete(Request $request, Menu $menu, MenuRepository $menuRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$menu->getId(), $request->request->get('_token'))) {
            $menuRepository->remove($menu, true);
        }

        return $this->redirectToRoute('app_menu_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/menu/_delete_form.html.twig
<form method="post" action="{{ path('app_menu_delete', {'id': menu.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ menu.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/menu/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/menu/edit.html.twig
{% block title %}Edit Menu{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}

{% block body %}
    <h1>Edit Menu</h1>

    {{ include('menu/_form.html.twig', {'button_label': 'Update'}) }}
<button class="btn btn-warning">

    <a href="{{ path('app_menu_index') }}">back to list</a>
</button>
    {{ include('menu/_delete_form.html.twig') }}
{% endblock %}

templates/menu/index.html.twig
{% block title %}Menu index{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}

{% block body %}
    <h1>Menu index</h1>

    <table class="table table-success table-striped">
        <tbody>
        {% for menu in menus %}
            <tr>
                  <tr>
                <th>Id</th>
                <td>{{ menu.id }}</td>
            </tr>
            <tr>
                <th>Libellé</th>
                <td>{{ menu.libelle }}</td>
            </tr>
            <tr>
                <th>Id_restaurant</th>
                <td>{{ menu.idRestaurant }}</td>
            </tr>
            <td>actions</td>
            <td>
                    <a href="{{ path('app_menu_show', {'id': menu.id}) }}">show</a>
                    <a href="{{ path('app_menu_edit', {'id': menu.id}) }}">edit</a>
                   <a href="{{ path('app_menu_new') }}">Create new</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/menu/new.html.twig
{% block title %}New Menu{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}
{% block body %}
    <h1>Create new Menu</h1>

    {{ include('menu/_form.html.twig') }}

    <a href="{{ path('app_menu_index') }}">back to list</a>
{% endblock %}

templates/menu/show.html.twig
{% block title %}Menu{% endblock %}
{% block head %}<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">{% endblock %}
{% block body %}
    <h1>Menu</h1>

    <table class="table table-success table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ menu.id }}</td>
            </tr>
            <tr>
                <th>Libellé</th>
                <td>{{ menu.libelle }}</td>
            </tr>
            <tr>
                <th>Id_restaurant</th>
                <td>{{ menu.idRestaurant }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_menu_index') }}">back to list</a>

    <a href="{{ path('app_menu_edit', {'id': menu.id}) }}">edit</a>

    {{ include('menu/_delete_form.html.twig') }}
{% endblock %}